/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Flitz
 */
public class ProjectDialogScreen extends javax.swing.JDialog {

    /**
     * Creates new form ProjectDialogScreen
     */
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelHeaderProjectDialog = new javax.swing.JPanel();
        JLabelHeaderProjectDialog = new javax.swing.JLabel();
        JPanelMainProjectDialog = new javax.swing.JPanel();
        JPanelForm = new javax.swing.JPanel();
        JLabelName = new javax.swing.JLabel();
        JTextFieldName = new javax.swing.JTextField();
        JLabelDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(10, 11, 28));

        JPanelHeaderProjectDialog.setBackground(new java.awt.Color(10, 11, 28));

        JLabelHeaderProjectDialog.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        JLabelHeaderProjectDialog.setForeground(new java.awt.Color(252, 252, 252));
        JLabelHeaderProjectDialog.setText("Projeto");

        javax.swing.GroupLayout JPanelHeaderProjectDialogLayout = new javax.swing.GroupLayout(JPanelHeaderProjectDialog);
        JPanelHeaderProjectDialog.setLayout(JPanelHeaderProjectDialogLayout);
        JPanelHeaderProjectDialogLayout.setHorizontalGroup(
            JPanelHeaderProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHeaderProjectDialogLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JLabelHeaderProjectDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        JPanelHeaderProjectDialogLayout.setVerticalGroup(
            JPanelHeaderProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHeaderProjectDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLabelHeaderProjectDialog)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JPanelMainProjectDialog.setBackground(new java.awt.Color(10, 11, 28));

        JPanelForm.setBackground(new java.awt.Color(10, 11, 28));
        JPanelForm.setForeground(new java.awt.Color(252, 252, 252));

        JLabelName.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JLabelName.setForeground(new java.awt.Color(252, 252, 255));
        JLabelName.setText("Nome");

        JTextFieldName.setBackground(new java.awt.Color(24, 24, 50));
        JTextFieldName.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        JTextFieldName.setForeground(new java.awt.Color(252, 252, 252));
        JTextFieldName.setBorder(null);
        JTextFieldName.setMargin(new java.awt.Insets(5, 6, 5, 6));
        JTextFieldName.setSelectedTextColor(new java.awt.Color(252, 252, 252));
        JTextFieldName.setSelectionColor(new java.awt.Color(24, 24, 50));
        JTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldNameActionPerformed(evt);
            }
        });

        JLabelDescription.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JLabelDescription.setForeground(new java.awt.Color(252, 252, 252));
        JLabelDescription.setText("Descrição");

        jScrollPane1.setBackground(new java.awt.Color(24, 24, 50));
        jScrollPane1.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(24, 24, 50));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(252, 252, 252));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setMargin(new java.awt.Insets(5, 6, 5, 6));
        jTextArea1.setSelectedTextColor(new java.awt.Color(252, 252, 252));
        jTextArea1.setSelectionColor(new java.awt.Color(24, 24, 50));
        jScrollPane1.setViewportView(jTextArea1);

        JButtonSave.setBackground(new java.awt.Color(252, 252, 252));
        JButtonSave.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JButtonSave.setLabel("Salvar");
        JButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelFormLayout = new javax.swing.GroupLayout(JPanelForm);
        JPanelForm.setLayout(JPanelFormLayout);
        JPanelFormLayout.setHorizontalGroup(
            JPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(JTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JButtonSave)))
                .addContainerGap())
        );
        JPanelFormLayout.setVerticalGroup(
            JPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFormLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(JLabelDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(JButtonSave)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout JPanelMainProjectDialogLayout = new javax.swing.GroupLayout(JPanelMainProjectDialog);
        JPanelMainProjectDialog.setLayout(JPanelMainProjectDialogLayout);
        JPanelMainProjectDialogLayout.setHorizontalGroup(
            JPanelMainProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelMainProjectDialogLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        JPanelMainProjectDialogLayout.setVerticalGroup(
            JPanelMainProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMainProjectDialogLayout.createSequentialGroup()
                .addComponent(JPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelHeaderProjectDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPanelMainProjectDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelHeaderProjectDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JPanelMainProjectDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldNameActionPerformed

    private void JButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonSave;
    private javax.swing.JLabel JLabelDescription;
    private javax.swing.JLabel JLabelHeaderProjectDialog;
    private javax.swing.JLabel JLabelName;
    private javax.swing.JPanel JPanelForm;
    private javax.swing.JPanel JPanelHeaderProjectDialog;
    private javax.swing.JPanel JPanelMainProjectDialog;
    private javax.swing.JTextField JTextFieldName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
