package view;

import controller.ProjectDAO;
import controller.TaskDAO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;
import util.ButtonColumnCellRederer;
import util.StatusColumnCellRenderer;
import util.TaskTableModel;


public class MainScreen extends javax.swing.JFrame {

    DefaultListModel projectsModel;
    TaskTableModel tasksModel;

    ProjectDAO projectDAO;
    TaskDAO taskDAO;
    
    public MainScreen() {
        initComponents();

        initDataAccessObjects();
        initComponentsModel();
 
        decorateJTableTasks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelEmptyTasksLayout = new javax.swing.JPanel();
        JLabelEmptyListIcon = new javax.swing.JLabel();
        JLabelEmptyListTitle = new javax.swing.JLabel();
        JLabelEmptyListDescription = new javax.swing.JLabel();
        JPanelHeader = new javax.swing.JPanel();
        JLabelHeaderTitle = new javax.swing.JLabel();
        JLabelHeaderSubtitle = new javax.swing.JLabel();
        JPanelMain = new javax.swing.JPanel();
        JPanelProjects = new javax.swing.JPanel();
        JLabelProjectTitle = new javax.swing.JLabel();
        JLabelProjectAdd = new javax.swing.JLabel();
        JPanelTasks = new javax.swing.JPanel();
        JLabelTaskTitle = new javax.swing.JLabel();
        JLabelTaskAdd = new javax.swing.JLabel();
        JPanelProjectsList = new javax.swing.JPanel();
        JScrollPanelProjectsList = new javax.swing.JScrollPane();
        JListProjectsList = new javax.swing.JList<>();
        JPanelTasksList = new javax.swing.JPanel();
        JScrollPanelTasks = new javax.swing.JScrollPane();
        jTableTasks = new javax.swing.JTable();

        JPanelEmptyTasksLayout.setBackground(new java.awt.Color(24, 24, 50));

        JLabelEmptyListIcon.setBackground(new java.awt.Color(24, 24, 50));
        JLabelEmptyListIcon.setForeground(new java.awt.Color(252, 252, 252));
        JLabelEmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelEmptyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xxxlist.png"))); // NOI18N
        JLabelEmptyListIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JLabelEmptyListIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLabelEmptyListTitle.setBackground(new java.awt.Color(24, 24, 50));
        JLabelEmptyListTitle.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        JLabelEmptyListTitle.setForeground(new java.awt.Color(252, 252, 252));
        JLabelEmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelEmptyListTitle.setText("No Tasks here...");
        JLabelEmptyListTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLabelEmptyListDescription.setBackground(new java.awt.Color(24, 24, 50));
        JLabelEmptyListDescription.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        JLabelEmptyListDescription.setForeground(new java.awt.Color(139, 139, 139));
        JLabelEmptyListDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelEmptyListDescription.setText("Click the \"+\" button to enter a new Task.");
        JLabelEmptyListDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JLabelEmptyListDescription.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout JPanelEmptyTasksLayoutLayout = new javax.swing.GroupLayout(JPanelEmptyTasksLayout);
        JPanelEmptyTasksLayout.setLayout(JPanelEmptyTasksLayoutLayout);
        JPanelEmptyTasksLayoutLayout.setHorizontalGroup(
            JPanelEmptyTasksLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelEmptyTasksLayoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelEmptyTasksLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabelEmptyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelEmptyListDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelEmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanelEmptyTasksLayoutLayout.setVerticalGroup(
            JPanelEmptyTasksLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelEmptyTasksLayoutLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(JLabelEmptyListIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelEmptyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelEmptyListDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 11, 28));

        JPanelHeader.setBackground(new java.awt.Color(10, 11, 28));
        JPanelHeader.setForeground(new java.awt.Color(252, 252, 252));

        JLabelHeaderTitle.setFont(new java.awt.Font("Poppins", 1, 40)); // NOI18N
        JLabelHeaderTitle.setForeground(new java.awt.Color(252, 252, 252));
        JLabelHeaderTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check2-circle-by-bootstrap.png"))); // NOI18N
        JLabelHeaderTitle.setLabelFor(JLabelHeaderTitle);
        JLabelHeaderTitle.setText("Todo App");
        JLabelHeaderTitle.setIconTextGap(10);

        JLabelHeaderSubtitle.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        JLabelHeaderSubtitle.setForeground(new java.awt.Color(138, 139, 139));
        JLabelHeaderSubtitle.setLabelFor(JLabelHeaderSubtitle);
        JLabelHeaderSubtitle.setText("Organize your Projects and Tasks in a practical way");

        JPanelMain.setBackground(new java.awt.Color(10, 11, 28));
        JPanelMain.setForeground(new java.awt.Color(252, 252, 252));

        JPanelProjects.setBackground(new java.awt.Color(10, 11, 28));
        JPanelProjects.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 24, 50), 2, true));
        JPanelProjects.setPreferredSize(new java.awt.Dimension(200, 45));

        JLabelProjectTitle.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        JLabelProjectTitle.setForeground(new java.awt.Color(252, 252, 252));
        JLabelProjectTitle.setText("Projects");

        JLabelProjectAdd.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        JLabelProjectAdd.setForeground(new java.awt.Color(252, 252, 252));
        JLabelProjectAdd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JLabelProjectAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus-circle-by-bootstrap.png"))); // NOI18N
        JLabelProjectAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLabelProjectAdd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        JLabelProjectAdd.setIconTextGap(0);
        JLabelProjectAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabelProjectAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPanelProjectsLayout = new javax.swing.GroupLayout(JPanelProjects);
        JPanelProjects.setLayout(JPanelProjectsLayout);
        JPanelProjectsLayout.setHorizontalGroup(
            JPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelProjectsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JLabelProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(JLabelProjectAdd)
                .addGap(10, 10, 10))
        );
        JPanelProjectsLayout.setVerticalGroup(
            JPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelProjectsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLabelProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(JLabelProjectAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        JPanelTasks.setBackground(new java.awt.Color(10, 11, 28));
        JPanelTasks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 24, 50), 2, true));
        JPanelTasks.setForeground(new java.awt.Color(252, 252, 252));
        JPanelTasks.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        JLabelTaskTitle.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        JLabelTaskTitle.setForeground(new java.awt.Color(252, 252, 252));
        JLabelTaskTitle.setText("Tasks");

        JLabelTaskAdd.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        JLabelTaskAdd.setForeground(new java.awt.Color(252, 252, 252));
        JLabelTaskAdd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JLabelTaskAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus-circle-by-bootstrap.png"))); // NOI18N
        JLabelTaskAdd.setToolTipText("");
        JLabelTaskAdd.setAlignmentX(0.5F);
        JLabelTaskAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLabelTaskAdd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        JLabelTaskAdd.setIconTextGap(0);
        JLabelTaskAdd.setPreferredSize(new java.awt.Dimension(11, 29));
        JLabelTaskAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabelTaskAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPanelTasksLayout = new javax.swing.GroupLayout(JPanelTasks);
        JPanelTasks.setLayout(JPanelTasksLayout);
        JPanelTasksLayout.setHorizontalGroup(
            JPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTasksLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JLabelTaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(JLabelTaskAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        JPanelTasksLayout.setVerticalGroup(
            JPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabelTaskAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelTaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelProjectsList.setBackground(new java.awt.Color(24, 24, 50));
        JPanelProjectsList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 24, 50), 2, true));
        JPanelProjectsList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JScrollPanelProjectsList.setBackground(new java.awt.Color(24, 24, 50));
        JScrollPanelProjectsList.setBorder(null);
        JScrollPanelProjectsList.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

        JListProjectsList.setBackground(new java.awt.Color(24, 24, 50));
        JListProjectsList.setBorder(null);
        JListProjectsList.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        JListProjectsList.setForeground(new java.awt.Color(139, 139, 139));
        JListProjectsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JListProjectsList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JListProjectsList.setDoubleBuffered(true);
        JListProjectsList.setFixedCellHeight(42);
        JListProjectsList.setMaximumSize(new java.awt.Dimension(54, 150));
        JListProjectsList.setName(""); // NOI18N
        JListProjectsList.setSelectionBackground(new java.awt.Color(24, 24, 50));
        JListProjectsList.setSelectionForeground(new java.awt.Color(252, 252, 252));
        JListProjectsList.setVisibleRowCount(10);
        JListProjectsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JListProjectsListMouseClicked(evt);
            }
        });
        JScrollPanelProjectsList.setViewportView(JListProjectsList);

        javax.swing.GroupLayout JPanelProjectsListLayout = new javax.swing.GroupLayout(JPanelProjectsList);
        JPanelProjectsList.setLayout(JPanelProjectsListLayout);
        JPanelProjectsListLayout.setHorizontalGroup(
            JPanelProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelProjectsListLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JScrollPanelProjectsList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        JPanelProjectsListLayout.setVerticalGroup(
            JPanelProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelProjectsListLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JScrollPanelProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        JPanelTasksList.setBackground(new java.awt.Color(24, 24, 50));
        JPanelTasksList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 24, 50), 1, true));
        JPanelTasksList.setLayout(new java.awt.BorderLayout());

        JScrollPanelTasks.setBackground(new java.awt.Color(24, 24, 50));
        JScrollPanelTasks.setBorder(null);
        JScrollPanelTasks.setForeground(new java.awt.Color(252, 252, 252));
        JScrollPanelTasks.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N

        jTableTasks.setBackground(new java.awt.Color(24, 24, 50));
        jTableTasks.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTableTasks.setForeground(new java.awt.Color(252, 252, 252));
        jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Deadline", "Completed", "Edit", "Remove"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTasks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableTasks.setFillsViewportHeight(true);
        jTableTasks.setGridColor(new java.awt.Color(19, 19, 41));
        jTableTasks.setRowHeight(35);
        jTableTasks.setSelectionBackground(new java.awt.Color(19, 19, 41));
        jTableTasks.setSelectionForeground(new java.awt.Color(252, 252, 252));
        jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTasks.setShowGrid(false);
        jTableTasks.setShowHorizontalLines(true);
        jTableTasks.getTableHeader().setReorderingAllowed(false);
        jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTasksMouseClicked(evt);
            }
        });
        JScrollPanelTasks.setViewportView(jTableTasks);

        JPanelTasksList.add(JScrollPanelTasks, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout JPanelMainLayout = new javax.swing.GroupLayout(JPanelMain);
        JPanelMain.setLayout(JPanelMainLayout);
        JPanelMainLayout.setHorizontalGroup(
            JPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMainLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(JPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanelProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanelProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelTasksList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        JPanelMainLayout.setVerticalGroup(
            JPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(JPanelTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelTasksList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout JPanelHeaderLayout = new javax.swing.GroupLayout(JPanelHeader);
        JPanelHeader.setLayout(JPanelHeaderLayout);
        JPanelHeaderLayout.setHorizontalGroup(
            JPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanelHeaderLayout.createSequentialGroup()
                .addGroup(JPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelHeaderLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(JLabelHeaderTitle))
                    .addGroup(JPanelHeaderLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(JLabelHeaderSubtitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelHeaderLayout.setVerticalGroup(
            JPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHeaderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(JLabelHeaderTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelHeaderSubtitle)
                .addGap(30, 30, 30)
                .addComponent(JPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLabelProjectAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelProjectAddMouseClicked
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, true);
        projectDialogScreen.setVisible(true);
        
        projectDialogScreen.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                loadProjects();
            }
        });
    }//GEN-LAST:event_JLabelProjectAddMouseClicked

    private void JLabelTaskAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelTaskAddMouseClicked
        
        int indexSeletecProject = JListProjectsList.getSelectedIndex();
        if (indexSeletecProject != -1) {
            TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, true);

            Project project = (Project) projectsModel.get(JListProjectsList.getSelectedIndex());

            taskDialogScreen.setProject(project);
            taskDialogScreen.setVisible(true);

            taskDialogScreen.addWindowListener(new WindowAdapter() {
                public void windowClosed(WindowEvent e) {
                    int projectIndex = JListProjectsList.getSelectedIndex();
                    Project project = (Project) projectsModel.get(projectIndex);
                    loadTasks(project.getId());
                }
            });
        } else {
            JOptionPane.showMessageDialog(rootPane, "You must choose a project for this task", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_JLabelTaskAddMouseClicked

    private void jTableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTasksMouseClicked
        
        int rowIndex = jTableTasks.rowAtPoint(evt.getPoint());
        int columnIndex = jTableTasks.columnAtPoint(evt.getPoint());
        Task task = tasksModel.getTasks().get(rowIndex);

        switch (columnIndex) {
            case 1 -> {
            }
            case 3 -> taskDAO.update(task);
            case 4 -> JOptionPane.showMessageDialog(rootPane, "Edit task");
            case 5 -> {
                taskDAO.removeById(task.getId());
                tasksModel.getTasks().remove(task);
                
                int projectIndex = JListProjectsList.getSelectedIndex();
                Project project = (Project) projectsModel.get(projectIndex);
                loadTasks(project.getId());
            }
        }
        
    }//GEN-LAST:event_jTableTasksMouseClicked

    private void JListProjectsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListProjectsListMouseClicked
        
       int projectIndex = JListProjectsList.getSelectedIndex();
       Project project = (Project) projectsModel.get(projectIndex);
       loadTasks(project.getId());
        
    }//GEN-LAST:event_JListProjectsListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelEmptyListDescription;
    private javax.swing.JLabel JLabelEmptyListIcon;
    private javax.swing.JLabel JLabelEmptyListTitle;
    private javax.swing.JLabel JLabelHeaderSubtitle;
    private javax.swing.JLabel JLabelHeaderTitle;
    private javax.swing.JLabel JLabelProjectAdd;
    private javax.swing.JLabel JLabelProjectTitle;
    private javax.swing.JLabel JLabelTaskAdd;
    private javax.swing.JLabel JLabelTaskTitle;
    private javax.swing.JList<String> JListProjectsList;
    private javax.swing.JPanel JPanelEmptyTasksLayout;
    private javax.swing.JPanel JPanelHeader;
    private javax.swing.JPanel JPanelMain;
    private javax.swing.JPanel JPanelProjects;
    private javax.swing.JPanel JPanelProjectsList;
    private javax.swing.JPanel JPanelTasks;
    private javax.swing.JPanel JPanelTasksList;
    private javax.swing.JScrollPane JScrollPanelProjectsList;
    private javax.swing.JScrollPane JScrollPanelTasks;
    private javax.swing.JTable jTableTasks;
    // End of variables declaration//GEN-END:variables

    private void decorateJTableTasks() {
        JScrollPanelTasks.setBackground(new Color(24, 24, 50));
        JScrollPanelTasks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 24, 50)));

        jTableTasks.setBackground(new Color(24, 24, 50));
        jTableTasks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 19, 41)));

        jTableTasks.getTableHeader().setFont(new Font("Poppins", Font.BOLD, 14));
        jTableTasks.getTableHeader().setOpaque(false);
        jTableTasks.getTableHeader().setBackground(new Color(19, 19, 41));
        jTableTasks.getTableHeader().setForeground(new Color(252, 252, 252));
        jTableTasks.getTableHeader().setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 19, 41)));
        
        jTableTasks.getColumnModel().getColumn(2).setCellRenderer(new StatusColumnCellRenderer());
        
        jTableTasks.setAutoCreateRowSorter(false);
        
        jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int rowIndex = jTableTasks.rowAtPoint(evt.getPoint());
                int columnIndex = jTableTasks.columnAtPoint(evt.getPoint());

                if (columnIndex == 3) {
                    Task task = tasksModel.getTasks().get(rowIndex);
                    taskDAO.update(task);
                }
            }
        });
    }
    
    private void initDataAccessObjects() {
        projectDAO = new ProjectDAO();
        taskDAO = new TaskDAO();
    }
    
    private void loadProjects() {
        List<Project> projects = projectDAO.getAll();

        projectsModel.clear();

        for (int i = 0; i < projects.size(); i++) {
            projectsModel.addElement(projects.get(i));
        }
        JListProjectsList.setModel(projectsModel);
    }
    
    private void loadTasks(int projectId) {
        List<Task> tasks = taskDAO.getByProjectId(projectId);

        tasksModel.setTasks(tasks);
        showJTableTasks(!tasks.isEmpty());
    }
    
    private void showJTableTasks(boolean isEmptyTable) {
        
        if (isEmptyTable) {
            if (JPanelEmptyTasksLayout.isVisible()) {
                JPanelEmptyTasksLayout.setVisible(false);
                JPanelTasksList.remove(JPanelEmptyTasksLayout);
            }

            JPanelTasksList.add(JScrollPanelTasks);
            JScrollPanelTasks.setVisible(true);
            JScrollPanelTasks.setSize(JPanelTasksList.getWidth(), JPanelTasksList.getHeight());
        } else {
            if (JScrollPanelTasks.isVisible()) {
                JScrollPanelTasks.setVisible(false);
                JPanelTasksList.remove(JScrollPanelTasks);
            }

            JPanelTasksList.add(JPanelEmptyTasksLayout);
            JPanelEmptyTasksLayout.setVisible(true);
            JPanelEmptyTasksLayout.setSize(JPanelTasksList.getWidth(), JPanelTasksList.getHeight());
        }
    }
    
     private void initComponentsModel() {
        projectsModel = new DefaultListModel();
        loadProjects();

        tasksModel = new TaskTableModel();
        jTableTasks.setModel(tasksModel);
        jTableTasks.getColumnModel().getColumn(2).setCellRenderer(new StatusColumnCellRenderer());
        jTableTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRederer("edit"));
        jTableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRederer("delete"));

        if (!projectsModel.isEmpty()) {
            JListProjectsList.setSelectedIndex(0);
            int projectIndex = JListProjectsList.getSelectedIndex();
            Project project = (Project) projectsModel.get(projectIndex);
            loadTasks(project.getId());
        }
    }
    
}
