package view;

import controller.ProjectDAO;
import javax.swing.JOptionPane;
import model.Project;


public class ProjectDialogScreen extends javax.swing.JDialog {

    ProjectDAO projectDAO;

    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        projectDAO = new ProjectDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelHeaderProjectDialog = new javax.swing.JPanel();
        JLabelHeaderProjectDialog = new javax.swing.JLabel();
        JPanelMainProjectDialog = new javax.swing.JPanel();
        JPanelForm = new javax.swing.JPanel();
        JLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        JLabelDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        JButtonSaveProject = new javax.swing.JButton();
        JLabelCampoNameObrigatorio1 = new javax.swing.JLabel();
        JLabelCampoNameObrigatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(10, 11, 28));

        JPanelHeaderProjectDialog.setBackground(new java.awt.Color(10, 11, 28));

        JLabelHeaderProjectDialog.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        JLabelHeaderProjectDialog.setForeground(new java.awt.Color(252, 252, 252));
        JLabelHeaderProjectDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder-plus-by-bootstrap.png"))); // NOI18N
        JLabelHeaderProjectDialog.setText("Project");
        JLabelHeaderProjectDialog.setIconTextGap(10);

        javax.swing.GroupLayout JPanelHeaderProjectDialogLayout = new javax.swing.GroupLayout(JPanelHeaderProjectDialog);
        JPanelHeaderProjectDialog.setLayout(JPanelHeaderProjectDialogLayout);
        JPanelHeaderProjectDialogLayout.setHorizontalGroup(
            JPanelHeaderProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHeaderProjectDialogLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JLabelHeaderProjectDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        JPanelHeaderProjectDialogLayout.setVerticalGroup(
            JPanelHeaderProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHeaderProjectDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLabelHeaderProjectDialog)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JPanelMainProjectDialog.setBackground(new java.awt.Color(10, 11, 28));

        JPanelForm.setBackground(new java.awt.Color(10, 11, 28));
        JPanelForm.setForeground(new java.awt.Color(252, 252, 252));

        JLabelName.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JLabelName.setForeground(new java.awt.Color(252, 252, 255));
        JLabelName.setText("Name");

        jTextFieldName.setBackground(new java.awt.Color(24, 24, 50));
        jTextFieldName.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(252, 252, 252));
        jTextFieldName.setBorder(null);
        jTextFieldName.setMargin(new java.awt.Insets(5, 6, 5, 6));
        jTextFieldName.setSelectedTextColor(new java.awt.Color(252, 252, 252));
        jTextFieldName.setSelectionColor(new java.awt.Color(24, 24, 50));
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        JLabelDescription.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JLabelDescription.setForeground(new java.awt.Color(252, 252, 252));
        JLabelDescription.setText("Description");

        jScrollPane1.setBackground(new java.awt.Color(24, 24, 50));
        jScrollPane1.setBorder(null);

        jTextAreaDescription.setBackground(new java.awt.Color(24, 24, 50));
        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTextAreaDescription.setForeground(new java.awt.Color(252, 252, 252));
        jTextAreaDescription.setRows(5);
        jTextAreaDescription.setBorder(null);
        jTextAreaDescription.setMargin(new java.awt.Insets(5, 6, 5, 6));
        jTextAreaDescription.setSelectedTextColor(new java.awt.Color(252, 252, 252));
        jTextAreaDescription.setSelectionColor(new java.awt.Color(24, 24, 50));
        jScrollPane1.setViewportView(jTextAreaDescription);

        JButtonSaveProject.setBackground(new java.awt.Color(252, 252, 252));
        JButtonSaveProject.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JButtonSaveProject.setText("Save");
        JButtonSaveProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonSaveProjectMouseClicked(evt);
            }
        });
        JButtonSaveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSaveProjectActionPerformed(evt);
            }
        });

        JLabelCampoNameObrigatorio1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelCampoNameObrigatorio1.setForeground(new java.awt.Color(204, 0, 0));
        JLabelCampoNameObrigatorio1.setText("Campo obrigatório.");

        javax.swing.GroupLayout JPanelFormLayout = new javax.swing.GroupLayout(JPanelForm);
        JPanelForm.setLayout(JPanelFormLayout);
        JPanelFormLayout.setHorizontalGroup(
            JPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JButtonSaveProject))
                    .addGroup(JPanelFormLayout.createSequentialGroup()
                        .addComponent(JLabelCampoNameObrigatorio1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPanelFormLayout.setVerticalGroup(
            JPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFormLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelCampoNameObrigatorio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonSaveProject)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanelMainProjectDialogLayout = new javax.swing.GroupLayout(JPanelMainProjectDialog);
        JPanelMainProjectDialog.setLayout(JPanelMainProjectDialogLayout);
        JPanelMainProjectDialogLayout.setHorizontalGroup(
            JPanelMainProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelMainProjectDialogLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        JPanelMainProjectDialogLayout.setVerticalGroup(
            JPanelMainProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JLabelCampoNameObrigatorio.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelCampoNameObrigatorio.setForeground(new java.awt.Color(204, 0, 0));
        JLabelCampoNameObrigatorio.setText("Campo obrigatório.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelHeaderProjectDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPanelMainProjectDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(JLabelCampoNameObrigatorio)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelHeaderProjectDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JPanelMainProjectDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addComponent(JLabelCampoNameObrigatorio)
                    .addContainerGap(187, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void JButtonSaveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSaveProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonSaveProjectActionPerformed

    private void JButtonSaveProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonSaveProjectMouseClicked
        try {
            Project project = new Project();
            project.setName(jTextFieldName.getText());
            project.setDescription(jTextAreaDescription.getText());

            projectDAO.save(project);

            JOptionPane.showMessageDialog(rootPane, "Project successfully saved!");
            dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_JButtonSaveProjectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonSaveProject;
    private javax.swing.JLabel JLabelCampoNameObrigatorio;
    private javax.swing.JLabel JLabelCampoNameObrigatorio1;
    private javax.swing.JLabel JLabelDescription;
    private javax.swing.JLabel JLabelHeaderProjectDialog;
    private javax.swing.JLabel JLabelName;
    private javax.swing.JPanel JPanelForm;
    private javax.swing.JPanel JPanelHeaderProjectDialog;
    private javax.swing.JPanel JPanelMainProjectDialog;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
