
package view;

import controller.TaskDAO;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;


public class TaskDialogScreen extends javax.swing.JDialog {

    TaskDAO taskDAO;
    Project project;

    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        taskDAO = new TaskDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelHeaderProjectDialog = new javax.swing.JPanel();
        JLabelHeaderProjectDialog = new javax.swing.JLabel();
        JPanelMainProjectDialog = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNotes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        JButtonSaveTask = new javax.swing.JButton();
        jFormattedTextFieldDeadLine = new javax.swing.JFormattedTextField();
        JLabelCampoNameObrigatorio = new javax.swing.JLabel();
        JLabelCampoDeadlineObrigatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPanelHeaderProjectDialog.setBackground(new java.awt.Color(10, 11, 28));

        JLabelHeaderProjectDialog.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        JLabelHeaderProjectDialog.setForeground(new java.awt.Color(252, 252, 252));
        JLabelHeaderProjectDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/list-task-by-bootstrap.png"))); // NOI18N
        JLabelHeaderProjectDialog.setText("Task");
        JLabelHeaderProjectDialog.setIconTextGap(10);

        javax.swing.GroupLayout JPanelHeaderProjectDialogLayout = new javax.swing.GroupLayout(JPanelHeaderProjectDialog);
        JPanelHeaderProjectDialog.setLayout(JPanelHeaderProjectDialogLayout);
        JPanelHeaderProjectDialogLayout.setHorizontalGroup(
            JPanelHeaderProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHeaderProjectDialogLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JLabelHeaderProjectDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        JPanelHeaderProjectDialogLayout.setVerticalGroup(
            JPanelHeaderProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHeaderProjectDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLabelHeaderProjectDialog)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JPanelMainProjectDialog.setBackground(new java.awt.Color(10, 11, 28));

        jPanel1.setBackground(new java.awt.Color(10, 11, 28));
        jPanel1.setForeground(new java.awt.Color(252, 252, 252));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 252, 255));
        jLabel1.setText("Name");

        jTextFieldName.setBackground(new java.awt.Color(24, 24, 50));
        jTextFieldName.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(252, 252, 252));
        jTextFieldName.setBorder(null);
        jTextFieldName.setMargin(new java.awt.Insets(5, 6, 5, 6));
        jTextFieldName.setSelectedTextColor(new java.awt.Color(252, 252, 252));
        jTextFieldName.setSelectionColor(new java.awt.Color(24, 24, 50));
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 252, 252));
        jLabel2.setText("Description");

        jScrollPane1.setBackground(new java.awt.Color(24, 24, 50));
        jScrollPane1.setBorder(null);

        jTextAreaDescription.setBackground(new java.awt.Color(24, 24, 50));
        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTextAreaDescription.setForeground(new java.awt.Color(252, 252, 252));
        jTextAreaDescription.setRows(5);
        jTextAreaDescription.setBorder(null);
        jTextAreaDescription.setMargin(new java.awt.Insets(5, 6, 5, 6));
        jTextAreaDescription.setSelectedTextColor(new java.awt.Color(252, 252, 252));
        jTextAreaDescription.setSelectionColor(new java.awt.Color(24, 24, 50));
        jScrollPane1.setViewportView(jTextAreaDescription);

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 252, 255));
        jLabel3.setText("Deadline");

        jScrollPane2.setBackground(new java.awt.Color(24, 24, 50));
        jScrollPane2.setBorder(null);

        jTextAreaNotes.setBackground(new java.awt.Color(24, 24, 50));
        jTextAreaNotes.setColumns(20);
        jTextAreaNotes.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jTextAreaNotes.setForeground(new java.awt.Color(252, 252, 252));
        jTextAreaNotes.setRows(5);
        jTextAreaNotes.setBorder(null);
        jTextAreaNotes.setMargin(new java.awt.Insets(5, 6, 5, 6));
        jTextAreaNotes.setSelectedTextColor(new java.awt.Color(252, 252, 252));
        jTextAreaNotes.setSelectionColor(new java.awt.Color(24, 24, 50));
        jScrollPane2.setViewportView(jTextAreaNotes);

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 252, 252));
        jLabel4.setText("Notes");

        JButtonSaveTask.setBackground(new java.awt.Color(252, 252, 252));
        JButtonSaveTask.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JButtonSaveTask.setText("Save");
        JButtonSaveTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonSaveTaskMouseClicked(evt);
            }
        });
        JButtonSaveTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSaveTaskActionPerformed(evt);
            }
        });

        jFormattedTextFieldDeadLine.setBackground(new java.awt.Color(24, 24, 50));
        jFormattedTextFieldDeadLine.setBorder(null);
        jFormattedTextFieldDeadLine.setForeground(new java.awt.Color(252, 252, 252));
        jFormattedTextFieldDeadLine.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldDeadLine.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jFormattedTextFieldDeadLine.setMinimumSize(new java.awt.Dimension(64, 20));
        jFormattedTextFieldDeadLine.setPreferredSize(new java.awt.Dimension(64, 22));
        jFormattedTextFieldDeadLine.setSelectedTextColor(new java.awt.Color(252, 252, 252));
        jFormattedTextFieldDeadLine.setSelectionColor(new java.awt.Color(10, 11, 28));
        jFormattedTextFieldDeadLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDeadLineActionPerformed(evt);
            }
        });

        JLabelCampoNameObrigatorio.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelCampoNameObrigatorio.setForeground(new java.awt.Color(204, 0, 0));
        JLabelCampoNameObrigatorio.setText("Campo obrigatório.");

        JLabelCampoDeadlineObrigatorio.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelCampoDeadlineObrigatorio.setForeground(new java.awt.Color(204, 0, 0));
        JLabelCampoDeadlineObrigatorio.setText("Campo obrigatório.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JButtonSaveTask))
                    .addComponent(jFormattedTextFieldDeadLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelCampoNameObrigatorio)
                            .addComponent(JLabelCampoDeadlineObrigatorio))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelCampoNameObrigatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelCampoDeadlineObrigatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonSaveTask)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanelMainProjectDialogLayout = new javax.swing.GroupLayout(JPanelMainProjectDialog);
        JPanelMainProjectDialog.setLayout(JPanelMainProjectDialogLayout);
        JPanelMainProjectDialogLayout.setHorizontalGroup(
            JPanelMainProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMainProjectDialogLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        JPanelMainProjectDialogLayout.setVerticalGroup(
            JPanelMainProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMainProjectDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelHeaderProjectDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPanelMainProjectDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelHeaderProjectDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JPanelMainProjectDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void JButtonSaveTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSaveTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonSaveTaskActionPerformed

    private void JButtonSaveTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonSaveTaskMouseClicked
        
        try {
            Task task = new Task();
            task.setIdProject(project.getId());
            task.setName(jTextFieldName.getText());
            task.setDescription(jTextAreaDescription.getText());
            task.setNotes(jTextAreaNotes.getText());

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date deadline = null;
            
            try {
                deadline = dateFormat.parse(jFormattedTextFieldDeadLine.getText());
            } catch (ParseException ex) {
                Logger.getLogger(TaskDialogScreen.class.getName()).log(Level.SEVERE, null, ex);
            }

            task.setDeadline(deadline);
            task.setCompleted(false);
            taskDAO.save(task);

            JOptionPane.showMessageDialog(rootPane, "Task successfully saved!");
            this.dispose();
            
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
  
    }//GEN-LAST:event_JButtonSaveTaskMouseClicked

    private void jFormattedTextFieldDeadLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDeadLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDeadLineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonSaveTask;
    private javax.swing.JLabel JLabelCampoDeadlineObrigatorio;
    private javax.swing.JLabel JLabelCampoNameObrigatorio;
    private javax.swing.JLabel JLabelHeaderProjectDialog;
    private javax.swing.JPanel JPanelHeaderProjectDialog;
    private javax.swing.JPanel JPanelMainProjectDialog;
    private javax.swing.JFormattedTextField jFormattedTextFieldDeadLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextArea jTextAreaNotes;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

    void setProject(Project project) {
        this.project = project;
    }
   
}
